name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/bitnami/postgresql/data
